name: "ebusd add-on"
version: "1.0.0"
slug: "ebusd"
description: >
  This Add-on runs eBUSd, a daemon for handling communication with eBUS devices
  connected to a 2-wire bus system (“energy bus” used by numerous heating systems)
  USB and network eBUSd adapters are supported.
url: "https://github.com/piotrtobolski/ha-addons/tree/main/ebusd"
arch:
  - aarch64
  - amd64
  - armv7
  - i386
init: false
# image: "ghcr.io/piotrtobolski/{arch}-addon-ebusd"